### ISSUE TITLE
The deserialization fails [unrelated to Polly]

### ISSUE THREAD

**Issue by umeshkarthik** [App-vNext/Polly.Caching.Serialization.Json#6]
Could not create an instance of type Microsoft.AspNetCore.Mvc.IActionResult

**Comment by reisenberger** [comment]
This is a general question about JSON serialization/deserialization not related to Polly. I would suggest looking at general resources about deserializing JSON to and from an interface with NewtonSoft.Json.

Polly.Caching.Serialization.Json provides full control over how Newtonsoft.Json acts within it, by allowing you to set the `JsonSerializerSettings` to use, as [shown in our example here](https://github.com/App-vNext/Polly.Caching.Serialization.Json#how-to-use-the-pollycachingserializationjson-plugin). Depending how you want to serialize complex types and instances referenced via interfaces, choose an appropriate [TypeNameHandling setting](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm).
